language: rust

rust:
  - stable

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo test
  - cargo fmt --all -- --check

notifications:
  email:
    on_failure: change
    on_success: change
